### ISSUE TITLE
Add support for wikibase:rank

### ISSUE THREAD

**Issue by jb3-2** [maxlath/wikibase-edit#27]
Hi, I would like to update the rank of existing claims to 'normal' as well as create new claims with rank 'preferred'. 

Background: I'd like to add the official population count to quarters of the city of Basel Switzerland (Q28539166) using an automated data pipeline (to be created), thereby setting the rank of the latest population count to 'preferred' while demoting the formerly latest count's rank to 'normal'. I have not yet found a non-manual way to do this, is it easily dable using your node.js interface?

Thanks for any input, J.

**Comment by maxlath** [comment]
I'm not sure it can yet, but it's definitely a feature we should have, I can have a look at it in the coming weeks

**Comment by maxlath** [comment]
it is now possible to edit ranks using the [`entity.edit` function](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#edit-entity). so you could code a workflow of this kind:
```js
const wbk = require('wikibase-sdk')({ instance: 'https://www.wikidata.org' })
// See config https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#config for credentials
const wbEdit = require('wikibase-edit')({ instance: 'https://www.wikidata.org', credentials })
const fetch = require('node-fetch')

const baselId = 'Q28539166'
const newPopulationCount = 1000000
const newPopulationCountDate = '2019-10'

const url = wbk.getEntities({ ids: [ baselId ], props: 'claims' })

fetch(url)
.then(res => res.json())
.then(res => {
  // Get the current claims (P1082: population)
  const populationClaims = res.entities[baselId].claims.P1082 || []
  // Format them in the simpler format that is expected by the entity edit function
  const simplifiedPopulationClaims = wbk.simplify.propertyClaims(populationClaims, { keepAll: true })
  // Set all the current claims ranks to normal
  simplifiedPopulationClaims.forEach(claim => { claim.rank = 'normal' })
  // Add the new preferred value
  simplifiedPopulationClaims.push({
    rank: 'preferred',
    value: newPopulationCount,
    qualifiers: {
      P585: newPopulationCountDate
    }
  })
  // And save
  return wbEdit.entity.edit({
    id: baselId,
    claims: {
      P1082: simplifiedPopulationClaims
    }
  })
})
.catch(console.error)
```

**Comment by fire-rabbit-afk** [comment]
Wow thank you very much, your help is much appreciated! J.
