### ISSUE TITLE
Maxlag not supported

### ISSUE THREAD

**Issue by Smittyvb** [maxlath/wikibase-edit#32]
The [maxlag](https://www.mediawiki.org/wiki/Manual:Maxlag_parameter) URL parameter should be supported.

**Comment by maxlath** [comment]
doc: https://www.mediawiki.org/wiki/Manual:Maxlag_parameter

**Comment by maxlath** [comment]
a `maxlag` parameter can now be set in `v3.2.0`! see [documentation](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#maxlag)
