### ISSUE TITLE
OAuth error with wdEdit.claim.update(guid, value)

### ISSUE THREAD

**Issue by stefandesu** [maxlath/wikibase-edit#34]
I'm trying to update a specific claim whose guid I have with a new value, but I can't get it to work. 

```javascript
await wdEdit.claim.update(id, value)
```

My code includes a check that `value` is different from the claim's previous value. Also, other actions (`claim.add`, `claim.remove`, `qualifier.add/update/remove`) all work without problems. But `claim.update` always results in the following error:

```
Error: post err: The authorization headers in your request are not valid: Invalid signature
    at /Users/stefanp/repos/gbv/wikidata-jskos/node_modules/wikidata-edit/lib/request.js:115:17
    at tryCatcher (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/stefanp/repos/gbv/wikidata-jskos/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21) {
  body: {
    error: {
      code: 'mwoauth-invalid-authorization',
      info: 'The authorization headers in your ' +
        'request are not valid: Invalid ' +
        'signature',
      '*': 'See https://www.wikidata.org/w/api.php for API usage. ' +
        'Subscribe to the mediawiki-api-announce mailing list at ' +
        '&lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; ' +
        'for notice of API deprecations and breaking changes.'
    },
    servedby: 'mw1289'
  }
}
```

The OAuth credentials are definitely correct (because all other actions work), so this error is not really helpful. Running it with verbose output didn't give me any further insights either. Interestingly, it works when using username/password for authentication, even though, as I said, other actions work with the same OAuth credentials.

Any idea what it could be? Thanks!

**Comment by maxlath** [comment]
which version are you using?

**Comment by stefandesu** [comment]
2.9.3 via npm.

**Comment by stefandesu** [comment]
I just though I'd try out the same operation using wikibase-cli, and I got an interesting result which might help with the issue:

```bash
❯ wd uc Q4115189 P5748 '0' '1-2'
```
-> works

```bash
❯ wd uc 'Q4115189%24508B801C-6B1F-4D67-9863-39C267CBA355' '1-2'
old and new claim values can't be the same [ { oldValue: undefined, newValue: undefined } ]
```
-> doesn't work

**Comment by stefandesu** [comment]
I changed the authentication to username/password and it works directly with wikibase-edit as well, so it must have something to do with OAuth. It's weird because all the other actions work fine.

**Comment by stefandesu** [comment]
I took a closer look at the POST requests going out, but I'm if anything even more confused than before.

**`claim.update` for OAuth vs username/password**
The only differences are:
- `oauth` parameter (set for OAuth vs `undefined` for username/password)
- Cookie header (`''` for OAuth, actual cookie for username/password)

**OAuth `claim.update` vs. `claim.remove`**
The only differences are:
- `action` in url (obviously)
- `body` (also obviously)

Everything else is exactly the same, including having `''` as the Cookie header. But `claim.remove` works, while `claim.update` does not.

I also did an attempt on implementing `wbsetclaimvalue` instead of `wbsetclaim` for `claim.update` which resulted in the exact same error.

I'd be really grateful for any kind of help regarding this. We have the functionality already working, but only using `entity.edit`, so every change just shows "Updated item" in the Wikidata log. It would be much better to show "Created claim"/"Changed claim"/"Removed claim" so that others can see exactly what our application did there. (Although to be honest, it would be really neat to be able to set/update qualifiers together with the claim instead of doing it separately, but I might be able to implement that myself as soon as we get `claim.update` to work.)

**Comment by stefandesu** [comment]
@maxlath I set up a test repository that demonstrates the problem: https://github.com/stefandesu/wikibase-edit-claim-update-example

I hope that helps. I will also try to reproduce the issue without using wikibase-edit, just using the API directly. If it's a bug in Wikibase itself, it should fail as well.

**Comment by maxlath** [comment]
I could reproduce the issue with wikidatat-edit@v2.9.3, [updating to wikibase-edit@v3+](https://github.com/stefandesu/wikibase-edit-claim-update-example/pull/1) fixes the issue, could that work for you?

**Comment by stefandesu** [comment]
That totally works for us, thank you! I will migrate our code to v3 tomorrow. Sorry that I didn't notice the release, I would have tried it out if I had.

**Comment by stefandesu** [comment]
There was an issue with the OAuth configuration not being sent with the API request. I submitted a PR with the fix: #39

**Comment by stefandesu** [comment]
I guess it is a bug in Wikidata/Wikibase itself after all? The implementation for `claim.update` was changed so that it won't show as "Changed claim" in the Wikidata history, but rather as "‎Updated item". Our hope was to have it show as "Changed claim" to be as granular as possible. Do you have more information about this?

**Comment by maxlath** [comment]
@stefandesu this is likely to be because in the new version [`claim.update` uses `entity.edit` instead of `claim.set`](https://github.com/maxlath/wikibase-edit/blob/e83e20a/lib/claim/update.js#L57-L58) (I didn't had in mind that it would generate different summaries), as it's assumed to be more complete, but maybe this assumption should be verified

**Comment by stefandesu** [comment]
@maxlath Ah so it might not even have anything to do with this issue. What does "more complete" mean in this case? Should I create a new issue regarding this?

**Comment by maxlath** [comment]
@stefandesu "more complete" especially refers to the capacity to add ranks #27, but I need to check my assumption that the dedicated endpoints are less complete in that regard
