### ISSUE TITLE
non authentified edits

### ISSUE THREAD

**Issue by GiulioC** [maxlath/wikibase-edit#51]
Is it possible to anonymously create/edit an entity ?
When I omit the login credentials in the config file i get the error: 
```
Error: missing credentials
```
I was wondering if there is a different procedure for performing edits without authentication.

**Comment by maxlath** [comment]
it wouldn't be anonymous, just non-authentified and identified by IP address, do you have a use case where this is a desirable behavior? I think the default should be that credentials are expected, but if there is a use case, we could have a flag to be able to omit credentials without getting an error and edit as IP

**Comment by GiulioC** [comment]
We have a use case where users (i.e. institutions) are provided with a simplified form that lets them create or edit pages on Wikidata with ease. Such edits should be possible both with and without authentication.
It would be really helpful if there was a flag or a similar mechanism that allows non-authenticated edits.

**Comment by maxlath** [comment]
I added an anonymous mode in `v4.2.0`, see [`anonymous` flag in the config](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#general-config), can confirm that it works for you?

**Comment by GiulioC** [comment]
Works like a charm, thank you very much !
