### ISSUE TITLE
wikibase-edit from the browser

### ISSUE THREAD

**Issue by maxlath** [maxlath/wikibase-edit#52]
I don't have a use-case but I could imagine that it could exist, and as we are already using libs such as cross-fetch that optimize for browser compatibility, I thought that maybe we aren't that far, and I was WROONG :D

I'm having difficulties with bundlers due to the use of dynamic relative paths, such as
```js
require(`./${fnModulePath}`)
```
which bundlers don't seem to like at all:
* browserify: couldn't make [that hack](https://stackoverflow.com/a/27672458/3324977) work 
* parcel: [issue](https://github.com/parcel-bundler/parcel/issues/2124)

Possible solution: refactor `index.js` to require files before passing the exported functions to `requestWrapper` and `bundleWrapper`, so that those don't need to use dynamic paths

@SirkoS you recommended cross-fetch so that it could also be used in the browser, did you actually get to make it work in the browser?

**Comment by maxlath** [comment]
yeay, following 4ffa5ec, the bundling now works! the new blocking point is CORS requests, at least on Wikidata, I don't know for other Wikibase instances.

**Comment by SirkoS** [comment]
Actually my default setup is a combination of ESModules, babel, and Webpack. This lets me easily switch target environments (I recently had to support some specific IE and old FF versions) without having to change my code style or give up on the syntactic sugar newer JS versions provide.

So for dynamic imports I just add the respective [plugin](https://babeljs.io/docs/en/next/babel-plugin-syntax-dynamic-import.html) and I'm fine. 

Regarding the CORS issue: Not sure about the implications enabling that on the Wikidata instance. But on your local instances you could sure add that. If not via MediaWiki directly then via the web or proxy server.

**Comment by maxlath** [comment]
interesting. so I would consider this issue as solved, the CORS setup being out of scope I guess.
