### ISSUE TITLE
Error handling when Wikibase returns HTML instead of JSON

### ISSUE THREAD

**Issue by SirkoS** [maxlath/wikibase-edit#53]
Currently, when Wikibase returns an HTML error page instead of a JSON response, wikibase-edit will just return a generic error like

> SyntaxError: Unexpected token < in JSON at position 0

That's not really helpful, when trying to debug what's actually going wrong.

I'm not quite sure how an error in those cases should look like, as the HTML is not that well formed to extract the error message.

For now, I adapted the code as follows (but merely for my debugging right now):
https://github.com/maxlath/wikibase-edit/blob/master/lib/request/insistent_req.js#L48

```javascript
const parseBody = res => {
  return res.text()
  .then( (raw) => {
    try {
      return JSON.parse( raw );
    } catch(e) {
      throw new Error( 'Could not parse response: ' + raw );
    }
  })
  .then(resBody => {
    if (resBody.error != null) throw requestError(res, resBody)
    else return resBody
  })
}
```

PS: the root cause for the error seems to be within the wikibase-docker image I'm using. I guess my setup just cannot handle the import of the about 10k instances I try to push using 5 parallel threads.

**Comment by maxlath** [comment]
ouch, that's going to be hard to write a test for that one ^^ but I did encounter the same problem a while ago, and the JSON parsing error is indeed not helping

**Comment by SirkoS** [comment]
The testcase is rather easy to construct (I think) using [nock](https://www.npmjs.com/package/nock):

```javascript
require('should')
const { __ } = require('config')
const insistent_req = __.require('lib/request/insistent_req')
const nock = require( 'nock' )

describe.only('insistent_req', () => {
  it('should return an object', async () => {

    before( () => {
      nock('https://example.org')
        .get('/test')
        .reply(200, '<!doctype html>' );
    });

    await insistent_req( 'GET', { url: 'https://example.org' } )
      .should.be.rejectedWith(Error, { message: 'Error in response' });

  })
});
```

But I have no clue how that error message (or error for that matter) should look like.

**Comment by SirkoS** [comment]
Testing should be rather easy I guess when using [nock](https://github.com/nock/nock):

```javascript
require('should')
const { __ } = require('config')
const insistent_req = __.require('lib/request/insistent_req')
const nock = require( 'nock' )

describe.only('insistent_req', () => {

  beforeEach( () => {
    nock('https://example.org')
      .get('/')
      .reply(200, '<!doctype html>' );
  });

  it('should throw a proper error', async () => {
    await insistent_req( 'GET', { url: 'https://example.org' } )
      .should.be.rejectedWith(Error, { message: 'Error in response' });
  })
});
```

However, I still have no clue how the error (message) should look like

**Comment by maxlath** [comment]
do you think the behavior in this case should be that it retries the request some seconds later (as it already does in case of a maxlag error)?

**Comment by SirkoS** [comment]
At least for me, those errors are rather fatal, so I don't think the lib should automatically retry for them. 

The application might have more information and can then trigger the request again, if needed.

**Comment by maxlath** [comment]
so I published a patch (`v4.2.2`) that, in the case you described, returns
```js
err.name = 'wrong response format'
err.message = 'Could not parse response: <!DOCTYPE html>...'
```

as for the test, I first implemented it with `nock`, but actually we don't even need it, we just need the URL of a page that doesn't return JSON ^^ b3e70ea

**Comment by SirkoS** [comment]
> as for the test, I first implemented it with `nock`, but actually we don't even need it, we just need the URL of a page that doesn't return JSON ^^ [b3e70ea](https://github.com/maxlath/wikibase-edit/commit/b3e70eab52aecf1f488d5a6c3b3575cc5cf1de42)

I thought about that as well, but decided against that. The external URL is kind of an external dependency out of your control. So assuming their server is down for whatever reason, you would get a timeout error instead in that test, I know that this case is not very likely, but I saw no particular reason not to mock this and thus be independent from anything outside the repo (at least for this test).

**Comment by maxlath** [comment]
true. I'm kind of having an increased aversion to adding dependencies this days, due to all those noisy security warnings, and the care it takes to look at what you are actually installing and running. but in the case of nock, it seems rather acceptable, so I reverted the change (5b194a0)

**Comment by SirkoS** [comment]
another thing to note: I'm less skeptical about dev-dependencies: at least for me they usually run in confined environments (separate dev VM or docker containers) and thus are far less likely to cause any harm. 

however, for production dependencies I absolutely share your opinion,
