### ISSUE TITLE
Set a reference with P813

### ISSUE THREAD

**Issue by DavideAllavena** [maxlath/wikibase-edit#55]
I would like to add a reference to an existing claim with a retrived date. 
I the example i find how to add a reference with only a single snack:

```JAVASCRIPT
wbEdit.reference.set({
  guid: claimGuid,
  property: 'P143',
  value: 'Q8447'
})
```

How can I handle this?
Thank you very much

**Comment by DavideAllavena** [comment]
@maxlath am I missing something easy?

**Comment by maxlath** [comment]
@DavideAllavena no you're not, that's why it takes time for me to answer ^^

The previous implementation was not allowing it, so I had to work on it a bit (1ac06b3): the following is now possible in `v4.5.0`

```js
wbEdit.reference.set({
  guid: claimGuid,
  snaks: {
    P143: 'Q8447',
    P813: '2020-07-07'
})
```

**Comment by DavideAllavena** [comment]
Thank you very much @maxlath !!! :beers: and kudos to you!
