### ISSUE TITLE
Meaningless error

### ISSUE THREAD

**Issue by HKalbasi** [maxlath/wikibase-edit#58]
I currently gave:
```
FetchError: invalid json response body at https://www.wikidata.org/w/api.php?action=wbgetentities&ids=P580&format=json&props=info reason: Unexpected token < in JSON at position 0
```
Which I think is because of `Our servers are currently under maintenance or experiencing a technical problem` html page is send as a response. I think using `.text()` instead of `.json()` and converting the response to json manually and catch common errors is a better idea.

**Comment by maxlath** [comment]
Should now have been fixed by 7adec8d, patch published in `v4.8.2`. Feel welcome to re-open if the problem reoccures or isn't fully solved
