### ISSUE TITLE
Does `edit` supports references like `create` does?

### ISSUE THREAD

**Issue by alemela** [maxlath/wikibase-edit#66]
In [this](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#create-claim) example the documentation shows how to add refrences during the creation of an item. Is the same syntax supported also by `edit`?

With my attempts seems no, but maybe I'm doing something wrong:
```
wbEdit.entity.edit({
                  id: object.id,
                  claims: editObj,
                  references: [{ P143: 'Q19960422'}]
              }, requestConfig)
```
With the code above I do the alteration on the page but without adding any reference.

**Comment by maxlath** [comment]
[`claim.create`](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#create-claim) has a different interface than  [`entity.edit`](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#edit-entity) (which is instead the same as [`entity.create`](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#create-entity)): to set a reference using `entity.edit`, `references` needs to be set within the claim object, for example:
```js
wbEdit.entity.edit({
  id: 'Q4115189',
  claims: {
    P370: {
      // If this id (a.k.a. "claim guid") is absent, it will create a new claim instead of updating the existing one
      id: 'Q4115189$2974B735-9548-45DA-8CAF-72FD54453CB3'
      value: 'foo'
      // This will override any existing reference for that claim
      references: [{ P143: 'Q19960422'}]
    }
  },
}, requestConfig)
```

**Comment by alemela** [comment]
Thank you so much @maxlath it works like a charm.
