### ISSUE TITLE
Support the new WikibaseLocalMedia extension datatype

### ISSUE THREAD

**Issue by larjohn** [maxlath/wikibase-edit#76]
If I am not mistaken, the new data type should have the name `localMedia` (see https://github.com/ProfessionalWiki/WikibaseLocalMedia/blob/master/src/HookHandlers.php).

Can it be added to the known datatypes?

**Comment by maxlath** [comment]
Is there a public instance somewhere running with this extension? We could confirm the datatype name used from its `wbgetentities` endpoint

**Comment by larjohn** [comment]
I tried it in my fork and it worked locally. Can you provide a sample query to check it on my own instance?

**Comment by maxlath** [comment]
https://www.wikidata.org/w/api.php?action=wbgetentities&props=claims&format=json&ids=Q1

**Comment by maxlath** [comment]
Thanks, I added `localMedia` datatype in 385f096 and published it in `v4.15.0`: can you confirm that it works?

**Comment by larjohn** [comment]
I am currently running a batch script, I will try that tomorrow, by the time it has finished processing.

Thanks!

**Comment by larjohn** [comment]
Sorry about the delay, it is OK!
