### ISSUE TITLE
Support for EDTF statements

### ISSUE THREAD

**Issue by paulduchesne** [maxlath/wikibase-edit#80]
We are working on a project which would greatly benefit from support for writing [EDTF](https://github.com/ProfessionalWiki/WikibaseEdtf) statements. Was this something which was on the roadmap for `wikibase-edit`, or would it be appropriate for us to work on our own implementation and put together a pull request?

**Comment by maxlath** [comment]
I'm not aware of any plans for adding EDTF support, so you're welcome to send a PR!

**Comment by maxlath** [comment]
I would assume that https://github.com/maxlath/wikibase-edit/pull/84 solved this (published in `v7.2.0`), but I couldn't test it locally, so you are welcome to re-open the issue if that's not the case.
